apiVersion: v1
kind: Deployment
metadata:
  name: mavenuitest
  labels:
    app: mavenuitest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mavenuitest
  template: 
    metadata:
      labels:
        app: mavenuitest
    spec:  
  containers:
  - name: awsbatch1
    image: sujathajanga/image3
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenuitest
  labels:
    app: mavenuitest
spec:
  selector:
    app: mavenuitest
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
